### ISSUE TITLE
Problem Yaml

### ISSUE THREAD

**Issue by mupsje** [sourabhjaiswal/zmpt101b#1]
Hi, I like this code allot,
I'm trying to put inside ESPHome, maybe I do something wrong.

Please help me out with this one.

I put the files inside the ESPhome folder and created also the sensor.h

but when I created the yaml. I get the follow error.

Thanks for taking time for me. 

Greets from Holland

![image](https://user-images.githubusercontent.com/46684538/140745765-af5258c9-3d9e-454a-9bcc-76ff46b641bb.png)

```
esphome:
  name: sensor
  platform: ESP32
  board: esp32dev
  includes:
  - sensor.h
  - ZMPT101B.h
  - ZMPT101B.cpp


wifi:
  networks:
  - ssid: **********
    password: *********
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32 power"
    password: "**********"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "**********"

captive_portal:

sensor:

- platform: zmpt101b
	  pin: 34
	  name: "Measured Voltage"
	  frequency: 50hz
	  num_of_samples: 50
	  calibration: 86
	  phase_shift: 1.7
```
